inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: '3.4'
  NewCops: enable

require:
  - rubocop-factory_bot
  - rubocop-rake
  - rubocop-rspec

Layout/LineLength:
  Max: 300
  Exclude:
    - 'spec/**/*'

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Metrics/AbcSize:
  Max: 80

Metrics/ClassLength:
  Max: 300

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/BlockLength:
  Max: 100

Metrics/MethodLength:
  Max: 80

Metrics/ParameterLists:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 25

Style/FetchEnvVar:
  Enabled: false

Style/MinMaxComparison:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

RSpec/DescribedClass:
  Enabled: false

RSpec/ExampleLength:
  Max: 50

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 7

Style/NumericPredicate:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys
  EnforcedShorthandSyntax: always
