inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: '3.3'
  NewCops: enable

require:
  - rubocop-rake
  - rubocop-rspec

Layout/LineLength:
  Max: 300

Metrics/AbcSize:
  Max: 30

Metrics/ClassLength:
  Max: 200

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/BlockLength:
  Max: 100

Metrics/MethodLength:
  Max: 50

Metrics/ParameterLists:
  Max: 8

Metrics/PerceivedComplexity:
  Max: 14

Style/NumericLiterals:
  Enabled: false

RSpec/DescribedClass:
  Enabled: false

RSpec/ExampleLength:
  Max: 30

RSpec/MultipleExpectations:
  Enabled: false
