inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: '3.3'
  NewCops: enable

require:
  - rubocop-rake
  - rubocop-rspec

Layout/LineLength:
  Max: 300

Metrics/BlockLength:
  Max: 100

Metrics/MethodLength:
  Max: 20

Metrics/ParameterLists:
  Max: 8

Style/NumericLiterals:
  Enabled: false
