# frozen_string_literal: true

require_relative 'cosensee/version'
require_relative 'cosensee/error'
require_relative 'cosensee/bracket_serializer'
require_relative 'cosensee/html_encodable'
require_relative 'cosensee/link_encodable'

require_relative 'cosensee/bracket_parser'
require_relative 'cosensee/html_builder'
require_relative 'cosensee/line_parser'
require_relative 'cosensee/node/blank_bracket'
require_relative 'cosensee/node/code'
require_relative 'cosensee/node/codeblock'
require_relative 'cosensee/node/command_line'
require_relative 'cosensee/node/decorate_bracket'
require_relative 'cosensee/node/double_bracket'
require_relative 'cosensee/node/empty_bracket'
require_relative 'cosensee/node/external_link_bracket'
require_relative 'cosensee/node/formula_bracket'
require_relative 'cosensee/node/gyazo_image_bracket'
require_relative 'cosensee/node/hash_tag'
require_relative 'cosensee/node/icon_bracket'
require_relative 'cosensee/node/image_bracket'
require_relative 'cosensee/node/indent'
require_relative 'cosensee/node/internal_link_bracket'
require_relative 'cosensee/node/link'
require_relative 'cosensee/node/quote'
require_relative 'cosensee/node/text_bracket'
require_relative 'cosensee/node/youtube_bracket'
require_relative 'cosensee/page_store'
require_relative 'cosensee/page'
require_relative 'cosensee/parsed_bracket'
require_relative 'cosensee/parsed_line'
require_relative 'cosensee/project'
require_relative 'cosensee/tailwind_renderer'
require_relative 'cosensee/tailwind_renderer/blank_bracket'
require_relative 'cosensee/tailwind_renderer/code'
require_relative 'cosensee/tailwind_renderer/codeblock_builder'
require_relative 'cosensee/tailwind_renderer/command_line'
require_relative 'cosensee/tailwind_renderer/decorate_bracket'
require_relative 'cosensee/tailwind_renderer/double_bracket'
require_relative 'cosensee/tailwind_renderer/empty_bracket'
require_relative 'cosensee/tailwind_renderer/external_link_bracket'
require_relative 'cosensee/tailwind_renderer/formula_bracket'
require_relative 'cosensee/tailwind_renderer/gyazo_image_bracket'
require_relative 'cosensee/tailwind_renderer/hash_tag'
require_relative 'cosensee/tailwind_renderer/icon_bracket'
require_relative 'cosensee/tailwind_renderer/image_bracket'
require_relative 'cosensee/tailwind_renderer/internal_link_bracket'
require_relative 'cosensee/tailwind_renderer/link'
require_relative 'cosensee/tailwind_renderer/page'
require_relative 'cosensee/tailwind_renderer/parsed_line'
require_relative 'cosensee/tailwind_renderer/quote'
require_relative 'cosensee/tailwind_renderer/text_bracket'
require_relative 'cosensee/tailwind_renderer/youtube_bracket'
require_relative 'cosensee/user'

module Cosensee
  MAX_SUMMARY_LINE = 10
end
